### ISSUE TITLE
¿Qué os parece si cambiáis el footer?

### ISSUE THREAD

**Issue by theavhd** [duoestudios/ketty#4]
Cambiar el footer de: Ketty | 2.20.8 | The Octopus Project 2020 a Ketty | 3.02.1 | duoestudios 2020?

**Comment by alexandrumuntenas** [comment]
La verdad que es una buena idea, no lo había pensado. Lo cambiaremos para la próxima versión!

**Comment by theavhd** [comment]
Genial! Estoy a la espera!
